name: Scrape ForexFactory Calendar

on:
  workflow_dispatch:
    inputs:
      start_date:
        description: 'Start date YYYY-MM-DD'
        required: false
      days:
        description: 'Days to scrape'
        required: false
        default: '7'
  schedule:
    - cron: '0 6 * * 1' # Weekly on Monday at 6 AM UTC (optional)

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install Chrome
      uses: browser-actions/setup-chrome@latest
    
    - name: Install dependencies
      run: |
        pip install selenium beautifulsoup4 webdriver-manager
    
    - name: Run scraper
      run: |
        ARGS=""
        if [ -n "${{ github.event.inputs.start_date }}" ]; then ARGS="$ARGS --start-date ${{ github.event.inputs.start_date }}"; fi
        if [ -n "${{ github.event.inputs.days }}" ]; then ARGS="$ARGS --days ${{ github.event.inputs.days }}"; fi
        echo "Running: python scraper.py $ARGS"
        python scraper.py $ARGS
    
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff --quiet && git diff --staged --quiet || git commit -m "Update forex calendar data [skip ci]"
        git push
