name: Scrape ForexFactory Calendar

on:
  schedule:
    # Runs every Monday at 6 AM UTC
    - cron: '0 6 * * 1'
  workflow_dispatch: # Allow manual trigger from GitHub UI

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install Chrome
      uses: browser-actions/setup-chrome@latest
    
    - name: Install dependencies
      run: |
        pip install selenium beautifulsoup4 pandas webdriver-manager
    
    - name: Run scraper
      run: |
        python scraper.py
    
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff --quiet && git diff --staged --quiet || git commit -m "Update forex calendar data [skip ci]"
        git push
